"""imagenes adicionales de producto e imagen de categoria

Revision ID: 22c47e665e03
Revises: 8201c162a243
Create Date: 2026-07-20 16:17:24.112235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c47e665e03'
down_revision = '8201c162a243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=300), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagenes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagenes')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
