"""Producto personalizable e instrucciones, especificaciones en detalle

Revision ID: 45ed1c9fdd0c
Revises: 22c47e665e03
Create Date: 2026-07-22 17:11:00.701518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ed1c9fdd0c'
down_revision = '22c47e665e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especificaciones', sa.Text(), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personalizable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('instrucciones_personalizacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('instrucciones_personalizacion')
        batch_op.drop_column('personalizable')

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_column('especificaciones')

    # ### end Alembic commands ###
